void beginLEDs() {
  leds.begin();
  leds2.begin();
  leds3.begin();
  leds4.begin();
  leds5.begin();
  leds6.begin();
  leds7.begin();
  leds8.begin();
  leds9.begin();
  leds10.begin();
  leds11.begin();
  leds12.begin();
  leds13.begin();
  leds14.begin();
  leds15.begin();
  leds16.begin();
  leds17.begin();
  leds18.begin();
  leds19.begin();
  leds20.begin();
  leds21.begin();
  leds22.begin();
  leds22.begin();
  leds23.begin();
  leds24.begin();
  leds25.begin();
//  leds26.begin();
//  leds27.begin();
//  leds28.begin();
//  leds29.begin();
//  leds30.begin();
//  leds31.begin();
//  leds32.begin();
}

void showLEDs() {
  leds.show();
  leds2.show();
  leds3.show();
  leds4.show();
  leds5.show();
  leds6.show();
  leds7.show();
  leds8.show();
  leds9.show();
  leds10.show();
  leds11.show();
  leds12.show();
  leds13.show();
  leds14.show();
  leds15.show();
  leds16.show();
  leds17.show();
  leds18.show();
  leds19.show();
  leds20.show();
  leds21.show();
  leds22.show();
  leds22.show();
  leds23.show();
  leds24.show();
  leds25.show();
//  leds26.show();
//  leds27.show();
//  leds28.show();
//  leds29.show();
//  leds30.show();
//  leds31.show();
//  leds32.show();
}
